! Prmtop parameter size definition
integer,parameter :: m_natom  =        8    ! number of max atom                   
integer,parameter :: m_ntype  =        2    ! number of atomtype                   
integer,parameter :: m_nres   =        1    ! number of residue                    
integer,parameter :: m_numbnd =        2    ! number of bond                       
integer,parameter :: m_numang =        2    ! number of angle                      
integer,parameter :: m_nptra  =        1    ! number of dihedral                   
integer,parameter :: m_nbonh  =        6    ! number of bond (including H)         
integer,parameter :: m_nbona  =        1    ! number of bond (without H)           
integer,parameter :: m_ntheth =       12    ! number of angle (including H)        
integer,parameter :: m_ntheta =        0    ! number of angle (without H)          
integer,parameter :: m_nphih  =        9    ! number of dihedral (including H)     
integer,parameter :: m_nphia  =        0    ! number of dihedral (including H)     
integer,parameter :: m_nnb    =       29    ! number of nonbon                     
integer,parameter :: m_nphb   =        0    ! number of 10-12 hydrogen bond types  
integer,parameter :: m_natyp  =        2    ! number of atomtypes in parameter file
