! Prmtop parameter size definition
integer,parameter :: m_natom  =      231    ! number of max atom                   
integer,parameter :: m_ntype  =        9    ! number of atomtype                   
integer,parameter :: m_nres   =       38    ! number of residue                    
integer,parameter :: m_numbnd =        9    ! number of bond                       
integer,parameter :: m_numang =       13    ! number of angle                      
integer,parameter :: m_nptra  =        5    ! number of dihedral                   
integer,parameter :: m_nbonh  =      152    ! number of bond (including H)         
integer,parameter :: m_nbona  =       41    ! number of bond (without H)           
integer,parameter :: m_ntheth =      266    ! number of angle (including H)        
integer,parameter :: m_ntheta =       10    ! number of angle (without H)          
integer,parameter :: m_nphih  =      130    ! number of dihedral (including H)     
integer,parameter :: m_nphia  =       18    ! number of dihedral (including H)     
integer,parameter :: m_nnb    =      629    ! number of nonbon                     
integer,parameter :: m_nphb   =        0    ! number of 10-12 hydrogen bond types  
integer,parameter :: m_natyp  =       10    ! number of atomtypes in parameter file
